### ISSUE TITLE
installation plv8 on ubuntu 18

### ISSUE THREAD

**Issue by Raidus** [plv8/plv8js#382]
Hey guys,

I am having trouble installing plv8 on `PostgreSQL 12.1 (Ubuntu 12.1-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit`.

I have done following steps

``` cmd
apt install -y libpq-dev
git clone https://github.com/plv8/plv8.git
cd plv8
git checkout r3.0alpha
sudo make PG_CONFIG=/usr/lib/postgresql/12/bin/
```

I'll get following errors

``` cmd
make: execvp: /usr/lib/postgresql/12/bin/: Permission denied
/bin/sh: 1: /usr/lib/postgresql/12/bin/: Permission denied
cat: '/pg_config*.h': No such file or directory
/bin/sh: 1: test: -ge: unexpected operator
/bin/sh: 1: test: -lt: unexpected operator
/bin/sh: 1: test: -lt: unexpected operator
/bin/sh: 1: test: -lt: unexpected operator
/bin/sh: 1: test: -lt: unexpected operator
mkdir -p build
cd build; git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
remote: Sending approximately 41.80 MiB ...
remote: Total 36486 (delta 23015), reused 36486 (delta 23015)
Receiving objects: 100% (36486/36486), 41.80 MiB | 26.37 MiB/s, done.
Resolving deltas: 100% (23015/23015), done.
cd build; fetch v8; cd v8; git checkout 7.4.288.28; gclient sync ; cd build/config ; cd ../.. ; tools/dev/v8gen.py x64.release -- is_component_build=false v8_static_library=true v8_use_snapshot=true v8_use_external_startup_data=false use_custom_libcxx=false v8_enable_i18n_support=false
Running: gclient root
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running depot tools as root is sad.
Running: gclient sync --with_branch_heads
Running depot tools as root is sad.
1>________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /root/plv8/build/_gclient_v8_kzhlOb' in '/root/plv8/build'
1>Cloning into '/root/plv8/build/_gclient_v8_kzhlOb'...
1>remote: Sending approximately 929.62 MiB ...
1>remote: Counting objects: 7660, done
1>remote: Total 730199 (delta 579156), reused 730199 (delta 579156)
1>Receiving objects: 100% (730199/730199), 929.36 MiB | 45.21 MiB/s, done.
1>Resolving deltas: 100% (579156/579156), done.

[0:01:30] Still working on:
[0:01:30]   v8
1>Syncing projects:   0% ( 0/ 2)
[0:01:30] Still working on:
[0:01:30]   v8
Syncing projects: 100% (27/27), done.
Running hooks:  20% ( 5/25) clang_format_linux
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' in '/root/plv8/build'
0> Downloading v8/buildtools/linux64/clang-format...
Downloading 1 files took 11.902650 second(s)
Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' took 11.94 secs
Running hooks:  32% ( 8/25) wasm_spec_tests
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/root/plv8/build'
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Extracting 413 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 3.474047 second(s)
Running hooks:  36% ( 9/25) wasm_js
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-js/tests.tar.gz.sha1' in '/root/plv8/build'
0> Downloading v8/test/wasm-js/tests.tar.gz...
0> Extracting 109 entries from v8/test/wasm-js/tests.tar.gz to v8/test/wasm-js/tests
Downloading 1 files took 3.153081 second(s)
Running hooks:  48% (12/25) sysroot_x86
________ running 'vpython v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/root/plv8/build'
Installing Debian sid i386 root image: /root/plv8/build/v8/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/06de352631feeb333ee9daa571e9e0646c2ef1ed/debian_sid_i386_sysroot.tar.xz
Running hooks:  52% (13/25) sysroot_x64
________ running 'vpython v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/root/plv8/build'
Installing Debian sid amd64 root image: /root/plv8/build/v8/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/9c905c99558f10e19cc878b5dca1d4bd58c607ae/debian_sid_amd64_sysroot.tar.xz
Running hooks:  72% (18/25) binutils
________ running 'vpython v8/third_party/binutils/download.py' in '/root/plv8/build'
0> Downloading /root/plv8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2...
Downloading 1 files took 3.261956 second(s)
Downloading /root/plv8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Extracting /root/plv8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Running hooks:  76% (19/25) clang
________ running 'vpython v8/tools/clang/scripts/update.py' in '/root/plv8/build'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-n332890-c2443155-1.tgz .......... Done.
Running hooks: 100% (25/25), done.
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
Previous HEAD position was 14b5b2ad82 Remove myself from WATCHLISTS
HEAD is now at 8a28642518 Version 7.4.288.28
Running depot tools as root is sad.
Syncing projects: 100% (24/24), done.

WARNING: 'v8/third_party/perfetto' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'v8/third_party/protobuf' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'v8/third_party/zlib' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.
Running hooks:   7% ( 2/28) landmines
________ running 'vpython v8/build/landmines.py --landmine-scripts v8/tools/get_landmines.py' in '/root/plv8/build'
Clobbering due to:
--- old_landmines	Sat Jan 18 17:42:20 2020
+++ new_landmines	Sat Jan 18 17:43:06 2020
@@ -18 +17,0 @@
-Clobber to possibly resolve build failure on Misc V8 Linux gcc.
Running hooks:  35% (10/28) gn_linux
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s v8/buildtools/linux64/gn.sha1' in '/root/plv8/build'
0> Downloading v8/buildtools/linux64/gn...
Downloading 1 files took 3.054919 second(s)
Running hooks:  39% (11/28) wasm_spec_tests
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/root/plv8/build'
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Removed v8/test/wasm-spec-tests/tests...
0> Extracting 72 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 4.095013 second(s)
Running hooks:  50% (14/28) sysroot_x86
________ running 'vpython v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/root/plv8/build'
Installing Debian sid i386 root image: /root/plv8/build/v8/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/9e6279438ece6fb42b5333ca90d5e9d0c188a403/debian_sid_i386_sysroot.tar.xz
Running hooks:  57% (16/28) sysroot_x64
________ running 'vpython v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/root/plv8/build'
Installing Debian sid amd64 root image: /root/plv8/build/v8/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/e7c53f04bd88d29d075bfd1f62b073aeb69cbe09/debian_sid_amd64_sysroot.tar.xz
Running hooks:  75% (21/28) clang
________ running 'vpython v8/tools/clang/scripts/update.py' in '/root/plv8/build'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-354873-1.tgz .......... Done.
Running hooks: 100% (28/28), done.

Hint: You can raise verbosity (-vv) to see the output of failed commands.

Traceback (most recent call last):
  File "tools/dev/v8gen.py", line 307, in <module>
    sys.exit(gen.main())
  File "tools/dev/v8gen.py", line 301, in main
    return self._options.func()
  File "tools/dev/v8gen.py", line 169, in cmd_gen
    gn_outdir,
  File "tools/dev/v8gen.py", line 211, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1
Makefile:35: recipe for target 'build/v8' failed
make: *** [build/v8] Error 1
```

Couldn't find any solution on the web. Any ideas?

Best
Wilhelm

**Comment by JerrySievert** [comment]
you need to make sure you have `pg_config` in your path and have permission to execute it.  that's the command that all extensions use to figure out how to compile the extension and where to put it.

the first 2 lines of your output tell you what's wrong:

```
make: execvp: /usr/lib/postgresql/12/bin/: Permission denied
/bin/sh: 1: /usr/lib/postgresql/12/bin/: Permission denied
```

you're trying to execute a directory, not an executable file.

**Comment by Raidus** [comment]
Oh yes. Thanks for pointing out. This was a copy&paste mistake.

However the build still fails. Here is the new error message

```
mkdir -p build
cd build; git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
remote: Sending approximately 41.80 MiB ...
remote: Total 36486 (delta 23015), reused 36486 (delta 23015)
Receiving objects: 100% (36486/36486), 41.80 MiB | 47.14 MiB/s, done.
Resolving deltas: 100% (23015/23015), done.
cd build; fetch v8; cd v8; git checkout 7.4.288.28; gclient sync ; cd build/config ; cd ../.. ; tools/dev/v8gen.py x64.release -- is_component_build=false v8_static_library=true v8_use_snapshot=true v8_use_external_startup_data=false use_custom_libcxx=false v8_enable_i18n_support=false
Running: gclient root
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running depot tools as root is sad.
Running: gclient sync --with_branch_heads
Running depot tools as root is sad.
1>________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /root/plv8/build/_gclient_v8_lg0CVo' in '/root/plv8/build'
1>Cloning into '/root/plv8/build/_gclient_v8_lg0CVo'...
1>remote: Sending approximately 929.62 MiB ...
1>remote: Counting objects: 7660, done
1>remote: Total 730199 (delta 579156), reused 730199 (delta 579156)
1>Receiving objects: 100% (730199/730199), 929.36 MiB | 46.30 MiB/s, done.
1>Resolving deltas: 100% (579156/579156), done.
1>Syncing projects:   0% ( 0/ 2)
[0:01:14] Still working on:
[0:01:14]   v8
Syncing projects: 100% (27/27), done.

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' in '/root/plv8/build'
0> Downloading v8/buildtools/linux64/clang-format...
Downloading 1 files took 3.775757 second(s)
Running hooks:  32% ( 8/25) wasm_spec_tests
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/root/plv8/build'
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Extracting 413 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 3.375672 second(s)
Running hooks:  36% ( 9/25) wasm_js
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-js/tests.tar.gz.sha1' in '/root/plv8/build'
0> Downloading v8/test/wasm-js/tests.tar.gz...
0> Extracting 109 entries from v8/test/wasm-js/tests.tar.gz to v8/test/wasm-js/tests
Downloading 1 files took 3.347070 second(s)
Running hooks:  48% (12/25) sysroot_x86
________ running 'vpython v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/root/plv8/build'
Installing Debian sid i386 root image: /root/plv8/build/v8/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/06de352631feeb333ee9daa571e9e0646c2ef1ed/debian_sid_i386_sysroot.tar.xz
Running hooks:  52% (13/25) sysroot_x64
________ running 'vpython v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/root/plv8/build'
Installing Debian sid amd64 root image: /root/plv8/build/v8/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/9c905c99558f10e19cc878b5dca1d4bd58c607ae/debian_sid_amd64_sysroot.tar.xz
Running hooks:  72% (18/25) binutils
________ running 'vpython v8/third_party/binutils/download.py' in '/root/plv8/build'
0> Downloading /root/plv8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2...
Downloading 1 files took 3.360941 second(s)
Downloading /root/plv8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Extracting /root/plv8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Running hooks:  76% (19/25) clang
________ running 'vpython v8/tools/clang/scripts/update.py' in '/root/plv8/build'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-n332890-c2443155-1.tgz .......... Done.
Running hooks: 100% (25/25), done.
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
Previous HEAD position was 14b5b2ad82 Remove myself from WATCHLISTS
HEAD is now at 8a28642518 Version 7.4.288.28
Running depot tools as root is sad.
Syncing projects: 100% (24/24), done.

WARNING: 'v8/third_party/perfetto' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'v8/third_party/protobuf' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'v8/third_party/zlib' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

________ running 'vpython v8/build/landmines.py --landmine-scripts v8/tools/get_landmines.py' in '/root/plv8/build'
Clobbering due to:
--- old_landmines	Sat Jan 18 17:53:10 2020
+++ new_landmines	Sat Jan 18 17:53:44 2020
@@ -18 +17,0 @@
-Clobber to possibly resolve build failure on Misc V8 Linux gcc.

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s v8/buildtools/linux64/gn.sha1' in '/root/plv8/build'
0> Downloading v8/buildtools/linux64/gn...
Downloading 1 files took 3.357187 second(s)
Running hooks:  39% (11/28) wasm_spec_tests
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/root/plv8/build'
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Removed v8/test/wasm-spec-tests/tests...
0> Extracting 72 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 4.308936 second(s)
Running hooks:  50% (14/28) sysroot_x86
________ running 'vpython v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/root/plv8/build'
Installing Debian sid i386 root image: /root/plv8/build/v8/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/9e6279438ece6fb42b5333ca90d5e9d0c188a403/debian_sid_i386_sysroot.tar.xz
Running hooks:  57% (16/28) sysroot_x64
________ running 'vpython v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/root/plv8/build'
Installing Debian sid amd64 root image: /root/plv8/build/v8/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/e7c53f04bd88d29d075bfd1f62b073aeb69cbe09/debian_sid_amd64_sysroot.tar.xz
Running hooks:  75% (21/28) clang
________ running 'vpython v8/tools/clang/scripts/update.py' in '/root/plv8/build'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-354873-1.tgz .......... Done.
Running hooks: 100% (28/28), done.

Hint: You can raise verbosity (-vv) to see the output of failed commands.

Traceback (most recent call last):
  File "tools/dev/v8gen.py", line 307, in <module>
    sys.exit(gen.main())
  File "tools/dev/v8gen.py", line 301, in main
    return self._options.func()
  File "tools/dev/v8gen.py", line 169, in cmd_gen
    gn_outdir,
  File "tools/dev/v8gen.py", line 211, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1
Makefile:35: recipe for target 'build/v8' failed
make: *** [build/v8] Error 1
```

**Comment by JerrySievert** [comment]
please make sure that `/usr/bin/python` is version 2, not version 3.

if it's version 2, you can `cd` into `build/v8` and execute the script that the v8 build is failing on by hand with higher verbosity to find out why v8 is choking:

```
/usr/bin/python -u tools/mb/mb.py gen -f infra/mb/mb_config.pyl -m developer_default -b x64.release out.gn/x64.release -vv
```

**Comment by Raidus** [comment]
Python2.7 is used on the linux machine. following your instructions, I'll get following message

```
Writing """\
is_debug = false
target_cpu = "x64"
""" to /root/plv8/build/v8/out.gn/x64.release/args.gn.

/root/plv8/build/v8/buildtools/linux64/gn gen out.gn/x64.release --check
  -> returned 1
ERROR at //build/config/linux/pkg_config.gni:103:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /root/plv8/build/v8/out.gn/x64.release/
Command: python /root/plv8/build/v8/build/config/linux/pkg-config.py -s /root/plv8/build/v8/build/linux/debian_sid_amd64-sysroot -a x64 glib-2.0 gmodule-2.0 gobject-2.0 gthread-2.0
Returned 1.
stderr:

Traceback (most recent call last):
  File "/root/plv8/build/v8/build/config/linux/pkg-config.py", line 246, in <module>
    sys.exit(main())
  File "/root/plv8/build/v8/build/config/linux/pkg-config.py", line 141, in main
    prefix = GetPkgConfigPrefixToStrip(options, args)
  File "/root/plv8/build/v8/build/config/linux/pkg-config.py", line 80, in GetPkgConfigPrefixToStrip
    "--variable=prefix"] + args, env=os.environ)
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

See //build/config/linux/BUILD.gn:89:3: whence it was called.
  pkg_config("glib") {
  ^-------------------
See //build/config/compiler/BUILD.gn:228:18: which caused the file to be included.
    configs += [ "//build/config/linux:compiler" ]
                 ^------------------------------
GN gen failed: 1
```

**Comment by JerrySievert** [comment]
you can follow the errors down:

```
/root/plv8/build/v8/build/config/linux/pkg-config.py -s /root/plv8/build/v8/build/linux/debian_sid_amd64-sysroot -a x64 glib-2.0 gmodule-2.0 gobject-2.0 gthread-2.0 -vv
```

as you might notice by now, v8's build system is rather painful.

**Comment by Raidus** [comment]
It's indeed a pain! 

Finally i was able to build it after installing all libs from https://chromium.googlesource.com/chromium/src/+/master/build/install-build-deps.sh

I have tried to create the extension via `CREATE EXTENSION plv8;` but it gives me `ERROR:  could not open extension control file "/usr/share/postgresql/12/extension/plv8.control": No such file or directory`

**Comment by Raidus** [comment]
when runnin `sudo make installcheck` I'll get

```
/usr/lib/postgresql/12/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/lib/postgresql/12/bin'    --dbname=contrib_regression init-extension plv8 plv8-errors inline json startup_pre startup varparam json_conv jsonb_conv window guc es6 arraybuffer composites currentresource startup_perms bytea find_function_perms memory_limits array_spread dialect bigint
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" ==============
psql: error: could not connect to server: FATAL:  role "root" does not exist
command failed: "/usr/lib/postgresql/12/bin/psql" -X -c "DROP DATABASE IF EXISTS \"contrib_regression\"" "postgres"
/usr/lib/postgresql/12/lib/pgxs/src/makefiles/pgxs.mk:420: recipe for target 'installcheck' failed
make: *** [installcheck] Error 2
```

**Comment by JerrySievert** [comment]
you need to run `make installcheck` with a user that has database access rights.

do you have an output of your `make install`?

**Comment by Raidus** [comment]
oh. totally forgot to `make install`. i should stop working for today ^^.

it's works! thank you so much for the great support! 🤘

**Comment by JerrySievert** [comment]
that'll do it :)
