### ISSUE TITLE
Build fails on Apple Silicon

### ISSUE THREAD

**Issue by KenSuenobu** [plv8/plv8js#422]
The issue with MacOSX 11 is that the version of v8's `find_sdk.py` script that gets checked out contains an error on line 72 in the `findall` function.  This should be changed from `MacOSX(10 ...` to `MacOSX(\d+\.\d+)\.sdk$`.  After doing this locally (with a strategically placed pause), I was able to get the build to compile.

Oddly enough, there is a checkout that has this very regex pattern in it, but it gets clobbered, seemingly by a possible cherry-picked version of v8.

If this line gets corrected, the entire build works perfectly.

**Comment by JerrySievert** [comment]
which version of plv8 are attempting to compile against?

the cherry-picked version of v8 is to specifically work around google's matching system for sdk's, which broke with an os update.  amusing that it should break again.

**Comment by KenSuenobu** [comment]
v2.3.15 from the documentation.  If there's a newer version, this may not apply any longer.  ;)

**Comment by JerrySievert** [comment]
well, there's 3.0alpha, which is pretty darned stable at this point - you can get it by checking out plv8 via git.  it uses a much newer version of v8.

**Comment by KenSuenobu** [comment]
Sure, I'll give it a try, as I'm on an M1 Mac now.  If it works, I'll close this issue.

**Comment by KenSuenobu** [comment]
Fails on M1 Mac:

```
[E2021-01-05T20:23:44.840784-07:00 38586 0 annotate.go:241] original error: exit status 100
[E2021-01-05T20:23:44.840842-07:00 38586 0 annotate.go:241]
[E2021-01-05T20:23:44.840850-07:00 38586 0 annotate.go:241] goroutine 1:
[E2021-01-05T20:23:44.840854-07:00 38586 0 annotate.go:241] #0 go.chromium.org/luci/vpython/venv/venv.go:615 - venv.(*Env).installVirtualEnv()
[E2021-01-05T20:23:44.840862-07:00 38586 0 annotate.go:241]   reason: failed to create VirtualEnv
[E2021-01-05T20:23:44.840867-07:00 38586 0 annotate.go:241]
[E2021-01-05T20:23:44.840870-07:00 38586 0 annotate.go:241] #1 go.chromium.org/luci/vpython/venv/venv.go:529 - venv.(*Env).createLocked.func2()
[E2021-01-05T20:23:44.840875-07:00 38586 0 annotate.go:241]   reason: failed to install VirtualEnv
[E2021-01-05T20:23:44.840879-07:00 38586 0 annotate.go:241]
[E2021-01-05T20:23:44.840883-07:00 38586 0 annotate.go:241] #2 go.chromium.org/luci/common/system/filesystem/tempdir.go:55 - filesystem.(*TempDir).With()
[E2021-01-05T20:23:44.840920-07:00 38586 0 annotate.go:241] #3 go.chromium.org/luci/vpython/venv/venv.go:103 - venv.withTempDir()
[E2021-01-05T20:23:44.841677-07:00 38586 0 annotate.go:241] #4 go.chromium.org/luci/vpython/venv/venv.go:515 - venv.(*Env).createLocked()
[E2021-01-05T20:23:44.841684-07:00 38586 0 annotate.go:241] #5 go.chromium.org/luci/vpython/venv/venv.go:272 - venv.(*Env).ensure.func1()
[E2021-01-05T20:23:44.841688-07:00 38586 0 annotate.go:241]   reason: failed to create new VirtualEnv
[E2021-01-05T20:23:44.841692-07:00 38586 0 annotate.go:241]
[E2021-01-05T20:23:44.841697-07:00 38586 0 annotate.go:241] #6 go.chromium.org/luci/vpython/venv/venv.go:995 - venv.mustReleaseLock()
[E2021-01-05T20:23:44.841701-07:00 38586 0 annotate.go:241] #7 go.chromium.org/luci/vpython/venv/venv.go:258 - venv.(*Env).ensure()
[E2021-01-05T20:23:44.842465-07:00 38586 0 annotate.go:241] #8 go.chromium.org/luci/vpython/venv/venv.go:154 - venv.With()
[E2021-01-05T20:23:44.842471-07:00 38586 0 annotate.go:241]   reason: failed to create empty probe environment
[E2021-01-05T20:23:44.842475-07:00 38586 0 annotate.go:241]
[E2021-01-05T20:23:44.842481-07:00 38586 0 annotate.go:241] #9 go.chromium.org/luci/vpython/run.go:62 - vpython.Run()
[E2021-01-05T20:23:44.842486-07:00 38586 0 annotate.go:241] #10 go.chromium.org/luci/vpython/application/application.go:320 - application.(*application).mainImpl()
[E2021-01-05T20:23:44.842490-07:00 38586 0 annotate.go:241] #11 go.chromium.org/luci/vpython/application/application.go:408 - application.(*Config).Main.func1()
[E2021-01-05T20:23:44.842494-07:00 38586 0 annotate.go:241] #12 go.chromium.org/luci/vpython/application/support.go:46 - application.run()
[E2021-01-05T20:23:44.843248-07:00 38586 0 annotate.go:241] #13 go.chromium.org/luci/vpython/application/application.go:407 - application.(*Config).Main()
[E2021-01-05T20:23:44.843254-07:00 38586 0 annotate.go:241] #14 vpython/main.go:109 - main.mainImpl()
[E2021-01-05T20:23:44.843258-07:00 38586 0 annotate.go:241] #15 vpython/main.go:115 - main.main()
[E2021-01-05T20:23:44.843262-07:00 38586 0 annotate.go:241] #16 runtime/proc.go:204 - runtime.main()
[E2021-01-05T20:23:44.843267-07:00 38586 0 annotate.go:241] #17 runtime/asm_amd64.s:1374 - runtime.goexit()
Error: Command 'vpython v8/third_party/depot_tools/update_depot_tools_toggle.py --disable' returned non-zero exit status 1 in /Volumes/Mac External/Users/kenji/Development/plv8/build

Hint: You can raise verbosity (-vv) to see the output of failed commands.

Traceback (most recent call last):
  File "tools/dev/v8gen.py", line 307, in <module>
    sys.exit(gen.main())
  File "tools/dev/v8gen.py", line 301, in main
    return self._options.func()
  File "tools/dev/v8gen.py", line 169, in cmd_gen
    gn_outdir,
  File "tools/dev/v8gen.py", line 211, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1
make: *** [build/v8] Error 1
```

**Comment by JerrySievert** [comment]
it looks like depot_tools, which is a v8 dependency, does not yet support apple silicon.  I found a couple of upstream-upstream bugs that may provide partial workarounds, but as I don't yet have an m1, I can't confirm:

https://bugs.chromium.org/p/chromium/issues/detail?id=1103275&q=component%3AInfra%3ESDK%20macos&can=2

https://bugs.chromium.org/p/chromium/issues/detail?id=1103275#c10

**Comment by KenSuenobu** [comment]
I can retry a build if you want - just let me know.

**Comment by JerrySievert** [comment]
I went ahead and adjusted the title, hopefully any apple silicon issues will land here until it's fixed.

**Comment by JerrySievert** [comment]
btw, likely any more attempts at building would likely be futile for now, unless you want to test your build times for fun.

I'll keep track of the upstream, hopefully it will be fixed soon - since plv8 uses head for `depot_tools` the fix should *just start working* for us.

**Comment by JerrySievert** [comment]
you're welcome to try https://github.com/JerrySievert/plv8 - the r3.0alpha branch (should be default).

it's a much newer version of v8.
