### ISSUE TITLE
python3.10 & jinja2 incompatibility  - compile error

### ISSUE THREAD

**Issue by hellower** [plv8/plv8js#480]
* python 3.9 - compile good.
* python 3.10  - error
 
```
[root@tnt-factory:/usr/local/src/plv8/build/v8/out.gn]
__STAGE__# python3 ../third_party/inspector_protocol/code_generator.py --jinja_dir ../third_party/ --output_base gen/src/inspector --config ../src/inspector/inspector_protocol_config.json --inspector_protocol_dir ///third_party/inspector_protocol
Traceback (most recent call last):
  File "/usr/local/src/plv8/build/v8/out.gn/../third_party/inspector_protocol/code_generator.py", line 702, in <module>
    main()
  File "/usr/local/src/plv8/build/v8/out.gn/../third_party/inspector_protocol/code_generator.py", line 584, in main
    jinja_env = initialize_jinja_env(jinja_dir, config.protocol.output, config)
  File "/usr/local/src/plv8/build/v8/out.gn/../third_party/inspector_protocol/code_generator.py", line 190, in initialize_jinja_env
    import jinja2
  File "/usr/local/src/plv8/build/v8/third_party/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/src/plv8/build/v8/third_party/jinja2/environment.py", line 16, in <module>
    from jinja2.defaults import BLOCK_START_STRING, \
  File "/usr/local/src/plv8/build/v8/third_party/jinja2/defaults.py", line 32, in <module>
    from jinja2.tests import TESTS as DEFAULT_TESTS
  File "/usr/local/src/plv8/build/v8/third_party/jinja2/tests.py", line 13, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
[root@tnt-factory:/usr/local/src/plv8/build/v8/out.gn]
```

known issue
```
https://github.com/nodejs/node/issues/39141
Bundled jinja2 is incompatible with Python 3.10 #39141
This issue was fixed in jinja2 2.10.2, so rebasing to a newer bundled copy would resolve the issue.
```

workaround:
sed -i -e 's@from collections import Mapping@from collections.abc import Mapping@g' ./build/v8/third_party/jinja2/tests.py

**Comment by JerrySievert** [comment]
I released 3.1.2, which updated the jinja2 hash.  testing with `Python 3.10.3`
